require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe UsersController do

  # This should return the minimal set of attributes required to create a valid
  # User. As you add validations to User, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { 
    "first_name" => "MyString", 
    "second_name" => "MyString",
    "email" => "test@test.com",
    "birthday" => 10.days.since,
    "shoe_size" => "54"
  } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # UsersController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all users as @users" do
      user = User.create! valid_attributes
      get :index, {}, valid_session
      assigns(:users).should eq([user])
    end
  end

  describe "GET show" do
    it "assigns the requested user as @user" do
      user = User.create! valid_attributes
      get :show, {:id => user.to_param}, valid_session
      assigns(:user).should eq(user)
    end
  end

  describe "GET new" do
    it "assigns a new user as @user" do
      get :new, {}, valid_session
      assigns(:user).should be_a_new(User)
    end
  end

  describe "POST create" do

    let(:valid_attributes) { { 
      "first_name" => "MyString", 
      "second_name" => "MyString",
      "email" => "test@test.com",
      "birthday" => "2008-05-21",
      "shoe_size" => "54"
    } }
    
    describe "with valid params" do
      it "creates a new User" do
        expect {
          post :create, {:user => valid_attributes}, valid_session
        }.to change(User, :count).by(1)
      end

      it "assigns a newly created user as @user" do
        post :create, {:user => valid_attributes}, valid_session
        assigns(:user).should be_a(User)
        assigns(:user).should be_persisted
      end

      it "redirects to the created user" do
        puts "-"*50
        puts "valid_attributes #{valid_attributes}"
        post :create, {:user => valid_attributes}, valid_session
        response.status.should == 201
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved user as @user" do
        # Trigger the behavior that occurs when invalid params are submitted
        User.any_instance.stub(:save).and_return(false)
        post :create, {:user => { "first_name" => "invalid value" }}, valid_session
        assigns(:user).should be_a_new(User)
      end
    end
  end

  describe "PUT update" do

    let(:valid_attributes) { { 
      "first_name" => "MyString", 
      "second_name" => "MyString",
      "email" => "test@test.com",
      "birthday" => {:year => '2008', :month => '11', :day => '22'},
      "shoe_size" => "54"
    } }

    describe "with valid params" do
      it "updates the requested user" do
        user = User.create! valid_attributes
        # Assuming there are no other users in the database, this
        # specifies that the User created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        User.any_instance.should_receive(:update_attributes).with({ "first_name" => "MyString" })
        put :update, {:id => user.to_param, :user => { "first_name" => "MyString" }}, valid_session
      end

      it "assigns the requested user as @user" do
        user = User.create! valid_attributes
        put :update, {:id => user.to_param, :user => valid_attributes}, valid_session
        assigns(:user).should eq(user)
      end

      it "update the user" do
        valid_attributes[:birthday] = 10.days.since
        user = User.create! valid_attributes
        put :update, {:id => user.to_param, :user => valid_attributes}, valid_session
        response.status.should == 204
      end
    end

    describe "with invalid params" do
      it "assigns the user as @user" do
        user = User.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        User.any_instance.stub(:save).and_return(false)
        put :update, {:id => user.to_param, :user => { "first_name" => "invalid value" }}, valid_session
        assigns(:user).should eq(user)
      end
    end
  end

  describe "DELETE destroy" do
    
    let(:valid_attributes) { { 
      "first_name" => "MyString", 
      "second_name" => "MyString",
      "email" => "test@test.com",
      "birthday" => {:year => '2008', :month => '11', :day => '22'},
      "shoe_size" => "54"
    } }

    it "destroys the requested user" do
      user = User.create! valid_attributes
      expect {
        delete :destroy, {:id => user.to_param}, valid_session
      }.to change(User, :count).by(-1)
    end

    it "destroys to the user" do
      user = User.create! valid_attributes
      delete :destroy, {:id => user.to_param}, valid_session
      response.status.should == 204
    end
  end

end
